var data = [
  {
   "id": 1,
   "genero": "masculino",
   "faixaEtaria": "adulto",
   "tipoProduto": "tênis",
   "nomeProduto": "Tênis Nike",
   "descricao": "Nike Vaporfly",
   "tamanhos": "38 a 43",
   "valor": 99.9,
   "quantParcelasSemJuros": 4,
   "filtroClassificacao": "all/masculino/adulto/tênis",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/1.jfif",
   "urlDrive": "https://drive.google.com/file/d/1liBJPZa8B1GUb9ZOQcmzsj-mlQjzpa7H/view?usp=share_link"
  },
  {
   "id": 90,
   "genero": "masculino",
   "faixaEtaria": "adulto",
   "tipoProduto": "tênis",
   "nomeProduto": "Tênis Lacoste",
   "descricao": "Lacoste Sport",
   "tamanhos": "43",
   "valor": 60.0,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/masculino/adulto/tênis",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/img100.jpeg",
   "urlDrive": "https://drive.google.com/file/d/1d9qx0u1x-JSwwZsR-OHC5mUR0MHQiF4y/view?usp=share_link"
  },
  {
   "id": 2,
   "genero": "masculino",
   "faixaEtaria": "adulto",
   "tipoProduto": "tênis",
   "nomeProduto": "Tênis Nike",
   "descricao": "Nike Vaporfly",
   "tamanhos": "38 a 43",
   "valor": 99.9,
   "quantParcelasSemJuros": 4,
   "filtroClassificacao": "all/masculino/adulto/tênis",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/2.jfif",
   "urlDrive": "https://drive.google.com/file/d/1y58zqs4wJWCMp5Roq_1b6VNwx5vIIg6e/view?usp=share_link"
  },
  {
   "id": 3,
   "genero": "masculino",
   "faixaEtaria": "adulto",
   "tipoProduto": "tênis",
   "nomeProduto": "Tênis Nike",
   "descricao": "Nike Vaporfly",
   "tamanhos": "38 a 43",
   "valor": 99.9,
   "quantParcelasSemJuros": 4,
   "filtroClassificacao": "all/masculino/adulto/tênis",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/3.jfif",
   "urlDrive": "https://drive.google.com/file/d/1YfahYG5nTLoYHgmfx75HJ-uor1HPA4SZ/view?usp=share_link"
  },
  {
   "id": 4,
   "genero": "masculino",
   "faixaEtaria": "adulto",
   "tipoProduto": "tênis",
   "nomeProduto": "Tênis Nike",
   "descricao": "Nike Vaporfly",
   "tamanhos": "38 a 43",
   "valor": 99.9,
   "quantParcelasSemJuros": 4,
   "filtroClassificacao": "all/masculino/adulto/tênis",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/4.jfif",
   "urlDrive": "https://drive.google.com/file/d/1-Qvy1lFitkUVST6eKIzzhxtGsgE5a0z3/view?usp=share_link"
  },
  {
   "id": 5,
   "genero": "masculino",
   "faixaEtaria": "adulto",
   "tipoProduto": "tênis",
   "nomeProduto": "Tênis Addidas",
   "descricao": "Tênis da Addidas",
   "tamanhos": "38 a 43",
   "valor": 99.9,
   "quantParcelasSemJuros": 4,
   "filtroClassificacao": "all/masculino/adulto/tênis",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/5.jfif",
   "urlDrive": "https://drive.google.com/file/d/12Nucu05dWEpZjHnOTm_Ojoy1D0OC0MM1/view?usp=sharing"
  },
  {
   "id": 6,
   "genero": "masculino",
   "faixaEtaria": "adulto",
   "tipoProduto": "tênis",
   "nomeProduto": "Tênis Addidas",
   "descricao": "Tênis da Addidas",
   "tamanhos": "38 a 43",
   "valor": 99.9,
   "quantParcelasSemJuros": 4,
   "filtroClassificacao": "all/masculino/adulto/tênis",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/6.jfif",
   "urlDrive": "https://drive.google.com/file/d/1W726suOK1S75eiOvP2ZyG8J7w-MY8J30/view?usp=share_link"
  },
  {
   "id": 7,
   "genero": "masculino",
   "faixaEtaria": "adulto",
   "tipoProduto": "tênis",
   "nomeProduto": "Air Jodan",
   "descricao": "Jordan MRV - Premium",
   "tamanhos": "38 a 43",
   "valor": 130,
   "quantParcelasSemJuros": 6,
   "filtroClassificacao": "all/masculino/adulto/tênis",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/7.jfif",
   "urlDrive": "https://drive.google.com/file/d/1e0rDG2qeRtUlBVVMVjbcWbqdn6ZwopDd/view?usp=share_link"
  },
  {
   "id": 8,
   "genero": "masculino",
   "faixaEtaria": "adulto",
   "tipoProduto": "tênis",
   "nomeProduto": "Air Jodan",
   "descricao": "Jordan MRV - Premium",
   "tamanhos": "38 a 43",
   "valor": 130,
   "quantParcelasSemJuros": 6,
   "filtroClassificacao": "all/masculino/adulto/tênis",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/8.jfif",
   "urlDrive": "https://drive.google.com/file/d/1mlkWvWhjtk4Ng9A2p7m6CpC-Mx-TrM39/view?usp=share_link"
  },
  {
   "id": 9,
   "genero": "masculino",
   "faixaEtaria": "adulto",
   "tipoProduto": "tênis",
   "nomeProduto": "Air Jodan",
   "descricao": "Jordan MRV - Premium",
   "tamanhos": "38 a 43",
   "valor": 130,
   "quantParcelasSemJuros": 6,
   "filtroClassificacao": "all/masculino/adulto/tênis",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/9.jfif",
   "urlDrive": "https://drive.google.com/file/d/1RJwN0QbRh7YmnRNCCYDKQxy1C4PrMHj7/view?usp=share_link"
  },
  {
   "id": 10,
   "genero": "masculino",
   "faixaEtaria": "adulto",
   "tipoProduto": "tênis",
   "nomeProduto": "Air Jodan",
   "descricao": "Jordan MRV - Premium",
   "tamanhos": "38 a 43",
   "valor": 130,
   "quantParcelasSemJuros": 6,
   "filtroClassificacao": "all/masculino/adulto/tênis",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/10.jfif",
   "urlDrive": "https://drive.google.com/file/d/1sFxP3WiZyNpPoIfKojk-oDTo7EsCI4bN/view?usp=share_link"
  },
  {
   "id": 11,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália Diversa",
   "descricao": "Sandália diversa",
   "tamanhos": "33 a 40",
   "valor": 46.99,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/11.jfif",
   "urlDrive": "https://drive.google.com/file/d/1fHCyQgETl7POEzm3zGAewNV8rTXqE8Cs/view?usp=share_link"
  },
  {
   "id": 12,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália Diversa",
   "descricao": "Sandália diversa",
   "tamanhos": "33 a 40",
   "valor": 46.99,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/12.jfif",
   "urlDrive": "https://drive.google.com/file/d/17mWPucjSvWUc5FZMTc_knon1ocz_I3UC/view?usp=share_link"
  },
  {
   "id": 13,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália Diversa",
   "descricao": "Sandália diversa",
   "tamanhos": "33 a 40",
   "valor": 46.99,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/13.jfif",
   "urlDrive": "https://drive.google.com/file/d/1vTicUmQiXk403OX6T0PftSjWg-AkxVaz/view?usp=share_link"
  },
  {
   "id": 14,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália Diversa",
   "descricao": "Sandália diversa",
   "tamanhos": "33 a 40",
   "valor": 46.99,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/14.jfif",
   "urlDrive": "https://drive.google.com/file/d/14RcemXr2x4pq85jgo1qQSDRxGLpPkbqn/view?usp=share_link"
  },
  {
   "id": 15,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália Diversa",
   "descricao": "Sandália diversa",
   "tamanhos": "33 a 40",
   "valor": 46.99,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/15.jfif",
   "urlDrive": "https://drive.google.com/file/d/1-_jOED0YVUAPVDigkxG7TtvOzab_MIlO/view?usp=share_link"
  },
  {
   "id": 16,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália Diversa",
   "descricao": "Sandália diversa",
   "tamanhos": "33 a 40",
   "valor": 46.99,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/16.jfif",
   "urlDrive": "https://drive.google.com/file/d/1JygZ8Tn2HDEwaesLEmNrJhM2wf9gtXwg/view?usp=share_link"
  },
  {
   "id": 17,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália Diversa",
   "descricao": "Sandália diversa",
   "tamanhos": "33 a 40",
   "valor": 46.99,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/17.jfif",
   "urlDrive": "https://drive.google.com/file/d/1J5rDibhZ83Go_kTMNisX3DpULQRgEwIF/view?usp=share_link"
  },
  {
   "id": 18,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália Diversa",
   "descricao": "Sandália diversa",
   "tamanhos": "33 a 40",
   "valor": 46.99,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/18.jfif",
   "urlDrive": "https://drive.google.com/file/d/1rHrCR9VK42qjvtLDI4XA9JfjoQCXHk6m/view?usp=share_link"
  },
  {
   "id": 19,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália Diversa",
   "descricao": "Sandália diversa",
   "tamanhos": "33 a 40",
   "valor": 46.99,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/19.jfif",
   "urlDrive": "https://drive.google.com/file/d/19XcNdtYVw_0brUvsWwwjH7TudRlVMywj/view?usp=share_link"
  },
  {
   "id": 20,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália Diversa",
   "descricao": "Sandália diversa",
   "tamanhos": "33 a 40",
   "valor": 46.99,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/20.jfif",
   "urlDrive": "https://drive.google.com/file/d/1yH1rNnhl9_JhJr9fZMyQgthRo3or7jwE/view?usp=share_link"
  },
  {
   "id": 21,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália Diversa",
   "descricao": "Sandália diversa",
   "tamanhos": "33 a 40",
   "valor": 46.99,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/21.jfif",
   "urlDrive": "https://drive.google.com/file/d/1clZLQdbRZZhn260DhPOY6jDptdc_qFAF/view?usp=share_link"
  },
  {
   "id": 22,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália Diversa",
   "descricao": "Sandália diversa",
   "tamanhos": "33 a 40",
   "valor": 46.99,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/22.jfif",
   "urlDrive": "https://drive.google.com/file/d/19VaL5WzlnxewHJJg4mTCG3A7jZs6uiqR/view?usp=share_link"
  },
  {
   "id": 23,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália Diversa",
   "descricao": "Sandália diversa",
   "tamanhos": "33 a 40",
   "valor": 46.99,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/23.jfif",
   "urlDrive": "https://drive.google.com/file/d/1VgdYk8QdVbzROKZnEWFia5_K0sy6YXPx/view?usp=share_link"
  },
  {
   "id": 24,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália Diversa",
   "descricao": "Sandália diversa",
   "tamanhos": "33 a 40",
   "valor": 46.99,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/24.jfif",
   "urlDrive": "https://drive.google.com/file/d/1ZDpCH0-1chzcCKxW_Zs92zyNBexhR6zA/view?usp=share_link"
  },
  {
   "id": 25,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália Diversa",
   "descricao": "Sandália diversa",
   "tamanhos": "33 a 40",
   "valor": 46.99,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/25.jfif",
   "urlDrive": "https://drive.google.com/file/d/1H85fuo2PC16T0KP-4LBWBu_346ty8ftd/view?usp=share_link"
  },
  {
   "id": 26,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália Diversa",
   "descricao": "Sandália diversa",
   "tamanhos": "33 a 40",
   "valor": 46.99,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/26.jfif",
   "urlDrive": "https://drive.google.com/file/d/1gjBWWFpLNL9aqgBNMTBbb3yRU_44eheO/view?usp=share_link"
  },
  {
   "id": 27,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": " Sandália Santa Lola",
   "descricao": "Santa Lola - Tradicional",
   "tamanhos": "33 a 40",
   "valor": 25.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/27.jfif",
   "urlDrive": "https://drive.google.com/file/d/1obv_pFoHKJ5AM7xSekAX7e-RULBVti7c/view?usp=share_link"
  },
  {
   "id": 28,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": " Sandália Santa Lola",
   "descricao": "Santa Lola - Tradicional",
   "tamanhos": "33 a 40",
   "valor": 25.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/28.jfif",
   "urlDrive": "https://drive.google.com/file/d/1G99w3Pk8oMckoxwzIQWHMRgML4enrkp5/view?usp=share_link"
  },
  {
   "id": 29,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": " Sandália Santa Lola",
   "descricao": "Santa Lola - Tradicional",
   "tamanhos": "33 a 40",
   "valor": 25.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/29.jfif",
   "urlDrive": "https://drive.google.com/file/d/15KdAeNmPlGPuzZo7ZBi-Bu3OBNe4wUih/view?usp=share_link"
  },
  {
   "id": 30,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": " Sandália Santa Lola",
   "descricao": "Santa Lola - Tradicional",
   "tamanhos": "33 a 40",
   "valor": 25.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/30.jfif",
   "urlDrive": "https://drive.google.com/file/d/14cKguqqbYxVeujdWJZ7qTm19IcMtpYR5/view?usp=share_link"
  },
  {
   "id": 31,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": " Sandália Santa Lola",
   "descricao": "Santa Lola - Tradicional",
   "tamanhos": "33 a 40",
   "valor": 25.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/31.jfif",
   "urlDrive": "https://drive.google.com/file/d/12k4Xnr-ugXz9f-qzZXLG9PY3bZ4XIa9-/view?usp=share_link"
  },
  {
   "id": 32,
   "genero": "feminino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sandálias",
   "nomeProduto": " Sandália Santa Lola",
   "descricao": "Santa Lola - Tradicional",
   "tamanhos": "33 a 40",
   "valor": 25.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/infantil/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/32.jfif",
   "urlDrive": "https://drive.google.com/file/d/1KEqgoweXNjxkFv0NEaP7zwul0691ajx4/view?usp=share_link"
  },
  {
   "id": 33,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": " Sandália Santa Lola",
   "descricao": "Santa Lola - Tradicional",
   "tamanhos": "33 a 40",
   "valor": 25.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/33.jfif",
   "urlDrive": "https://drive.google.com/file/d/1QyM1UqH8Nrjbg70K9DDMUx7sQ3pr3nq5/view?usp=share_link"
  },
  {
   "id": 34,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": " Sandália Santa Lola",
   "descricao": "Santa Lola - Tradicional",
   "tamanhos": "33 a 40",
   "valor": 25.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/34.jfif",
   "urlDrive": "https://drive.google.com/file/d/1ANrbnz1HLZGo7Lpi9rJXIevELjJreREe/view?usp=share_link"
  },
  {
   "id": 35,
   "genero": "feminino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sandálias",
   "nomeProduto": " Sandália Santa Lola",
   "descricao": "Santa Lola - Tradicional",
   "tamanhos": "33 a 40",
   "valor": 25.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/infantil/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/35.jfif",
   "urlDrive": "https://drive.google.com/file/d/1WyBLt09E5nZLtIz7ehD6XqnR7R2ZaDvm/view?usp=share_link"
  },
  {
   "id": 36,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": " Sandália Santa Lola",
   "descricao": "Santa Lola - Tradicional",
   "tamanhos": "33 a 40",
   "valor": 25.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/36.jfif",
   "urlDrive": "https://drive.google.com/file/d/1zPjR0YxE3NiLNfqdbdPFElsrUcc85zrc/view?usp=share_link"
  },
  {
   "id": 37,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": " Sandália Santa Lola",
   "descricao": "Santa Lola - Tradicional",
   "tamanhos": "33 a 40",
   "valor": 25.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/37.jfif",
   "urlDrive": "https://drive.google.com/file/d/1myE88p_JYFmMubv2KvspIuTHKs6QKzFI/view?usp=share_link"
  },
  {
   "id": 38,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": " Sandália Santa Lola",
   "descricao": "Santa Lola - Tradicional",
   "tamanhos": "33 a 40",
   "valor": 25.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/38.jfif",
   "urlDrive": "https://drive.google.com/file/d/1wy5W-HF9LXSgStivNDyQv6U8GE8b7uUO/view?usp=share_link"
  },
  {
   "id": 39,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": " Sandália Santa Lola",
   "descricao": "Santa Lola - Tradicional",
   "tamanhos": "33 a 40",
   "valor": 25.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/39.jfif",
   "urlDrive": "https://drive.google.com/file/d/1gI8EEJ-iZigA-yxM1f-mtvwUFV5O4L3p/view?usp=share_link"
  },
  {
   "id": 40,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": " Sandália Santa Lola",
   "descricao": "Santa Lola - Tradicional",
   "tamanhos": "33 a 40",
   "valor": 25.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/40.jfif",
   "urlDrive": "https://drive.google.com/file/d/1Z442Ezn-PT5rha51i7hWYblAH6nhODnk/view?usp=share_link"
  },
  {
   "id": 41,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": " Sandália Santa Lola",
   "descricao": "Santa Lola - Tradicional",
   "tamanhos": "33 a 40",
   "valor": 25.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/41.jfif",
   "urlDrive": "https://drive.google.com/file/d/1vx0OVosSA7ThsSe_PZTc5rlWujjasou7/view?usp=share_link"
  },
  {
   "id": 42,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": " Sandália Santa Lola",
   "descricao": "Santa Lola - Tradicional",
   "tamanhos": "33 a 40",
   "valor": 25.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/42.jfif",
   "urlDrive": "https://drive.google.com/file/d/1RL7JD3CLqwhBf6dtU9X0ZXG4f9Zew3Ju/view?usp=share_link"
  },
  {
   "id": 43,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": " Sandália Santa Lola",
   "descricao": "Santa Lola - Tradicional",
   "tamanhos": "33 a 40",
   "valor": 25.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/43.jfif",
   "urlDrive": "https://drive.google.com/file/d/1Ji5-e6__3S3ZySdjDiCfS_H6F5nY2-Ax/view?usp=share_link"
  },
  {
   "id": 44,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandálias",
   "nomeProduto": " Sandália Santa Lola",
   "descricao": "Santa Lola - Tradicional",
   "tamanhos": "33 a 40",
   "valor": 25.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/44.jfif",
   "urlDrive": "https://drive.google.com/file/d/1cksfCRF2jrMyoFHf2dmW2U5Xt8MEpFSk/view?usp=share_link"
  },
  {
   "id": 45,
   "genero": "feminino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sandálias",
   "nomeProduto": " Sandália Santa Lola",
   "descricao": "Santa Lola - Tradicional",
   "tamanhos": "33 a 40",
   "valor": 25.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/infantil/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/45.jfif",
   "urlDrive": "https://drive.google.com/file/d/1z_rfAuXfECD5oo2qIjnjo4KwsmiKvzWP/view?usp=share_link"
  },
  {
   "id": 46,
   "genero": "feminino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sandálias",
   "nomeProduto": " Sandália Santa Lola",
   "descricao": "Santa Lola - Tradicional",
   "tamanhos": "33 a 40",
   "valor": 25.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/infantil/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/46.jfif",
   "urlDrive": "https://drive.google.com/file/d/1i-r3AOSCb-7CqSf9uYEXPRDKqdKiTCJt/view?usp=share_link"
  },
  {
   "id": 47,
   "genero": "feminino",
   "faixaEtaria": "infantil",
   "tipoProduto": "tênis",
   "nomeProduto": "Tênis infantil",
   "descricao": "Tênis infantil",
   "tamanhos": "...",
   "valor": 35.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/infantil/tênis",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/47.jfif",
   "urlDrive": "https://drive.google.com/file/d/1gHawzBLFfux82Rg7GCaBVcPOlUWKEioy/view?usp=share_link"
  },
  {
   "id": 48,
   "genero": "feminino",
   "faixaEtaria": "infantil",
   "tipoProduto": "tênis",
   "nomeProduto": "Tênis infantil",
   "descricao": "Tênis infantil",
   "tamanhos": "...",
   "valor": 35.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/infantil/tênis",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/48.jfif",
   "urlDrive": "https://drive.google.com/file/d/1e985Vh4X_v8aZZNU1Wrob3_xi4hyfvzH/view?usp=share_link"
  },
  {
   "id": 49,
   "genero": "feminino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sapátos",
   "nomeProduto": "Sapato Infantil",
   "descricao": "Boby Love - Sapáto infantil",
   "tamanhos": "17 a 22",
   "valor": 45.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/infantil/Sapátos",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/49.jfif",
   "urlDrive": "https://drive.google.com/file/d/15_L0cmhaWadwX06FNGM_ZUyUtCKlJUzd/view?usp=share_link"
  },
  {
   "id": 50,
   "genero": "feminino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sapátos",
   "nomeProduto": "Sapato Infantil",
   "descricao": "Boby Love - Sapáto infantil",
   "tamanhos": "17 a 22",
   "valor": 45.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/infantil/Sapátos",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/50.jfif",
   "urlDrive": "https://drive.google.com/file/d/1SEJvDR4YIgLUByhmZ_UyR6bDFQNgJUDS/view?usp=share_link"
  },
  {
   "id": 51,
   "genero": "feminino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sapátos",
   "nomeProduto": "Sapato Infantil",
   "descricao": "Boby Love - Sapáto infantil",
   "tamanhos": "17 a 22",
   "valor": 45.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/infantil/Sapátos",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/51.jfif",
   "urlDrive": "https://drive.google.com/file/d/1ZhHBJM_EfdDrz2uJrLejGGzZLBq4H6k2/view?usp=share_link"
  },
  {
   "id": 52,
   "genero": "masculino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sapátos",
   "nomeProduto": "Sapato Infantil",
   "descricao": "Boby Love - Sapáto infantil",
   "tamanhos": "17 a 22",
   "valor": 45.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/masculino/infantil/Sapátos",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/52.jfif",
   "urlDrive": "https://drive.google.com/file/d/1OPclaw43Y4liIp8zd3AeWDKBkwE6ruOD/view?usp=share_link"
  },
  {
   "id": 53,
   "genero": "masculino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sapátos",
   "nomeProduto": "Sapato Infantil",
   "descricao": "Boby Love - Sapáto infantil",
   "tamanhos": "17 a 22",
   "valor": 45.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/masculino/infantil/Sapátos",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/53.jfif",
   "urlDrive": "https://drive.google.com/file/d/1OPclaw43Y4liIp8zd3AeWDKBkwE6ruOD/view?usp=share_link"
  },
  {
   "id": 54,
   "genero": "feminino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sapátos",
   "nomeProduto": "Sapato Infantil",
   "descricao": "Boby Love - Sapáto infantil",
   "tamanhos": "17 a 22",
   "valor": 45.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/infantil/Sapátos",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/54.jfif",
   "urlDrive": "https://drive.google.com/file/d/1UHey1wPCfCWT5d4owlnd2oj1ODmNkFI0/view?usp=share_link"
  },
  {
   "id": 55,
   "genero": "feminino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sapátos",
   "nomeProduto": "Sapato Infantil",
   "descricao": "Boby Love - Sapáto infantil",
   "tamanhos": "17 a 22",
   "valor": 45.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/infantil/Sapátos",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/55.jfif",
   "urlDrive": "https://drive.google.com/file/d/1nAejiqaDTljETpDUS0L_nT2_U3ll0dY5/view?usp=share_link"
  },
  {
   "id": 56,
   "genero": "masculino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sapátos",
   "nomeProduto": "Sapato Infantil",
   "descricao": "Boby Love - Sapáto infantil",
   "tamanhos": "17 a 22",
   "valor": 45.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/masculino/infantil/Sapátos",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/56.jfif",
   "urlDrive": "https://drive.google.com/file/d/1Ukyf1jdZmibOsmvK1_GAXmIbpUErgHH3/view?usp=share_link"
  },
  {
   "id": 57,
   "genero": "masculino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sapátos",
   "nomeProduto": "Sapato Infantil",
   "descricao": "Boby Love - Sapáto infantil",
   "tamanhos": "17 a 22",
   "valor": 45.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/masculino/infantil/Sapátos",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/57.jfif",
   "urlDrive": "https://drive.google.com/file/d/11IR74Hg_mMK209lK5jk_SFq4xh_nCjMl/view?usp=share_link"
  },
  {
   "id": 58,
   "genero": "masculino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sapátos",
   "nomeProduto": "Sapato Infantil",
   "descricao": "Boby Love - Sapáto infantil",
   "tamanhos": "17 a 22",
   "valor": 45.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/masculino/infantil/Sapátos",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/58.jfif",
   "urlDrive": "https://drive.google.com/file/d/1onR_vAEO6iPnrOmDoRGXk-Lp53c3JKF2/view?usp=share_link"
  },
  {
   "id": 59,
   "genero": "feminino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sapátos",
   "nomeProduto": "Sapato Infantil",
   "descricao": "Boby Love - Sapáto infantil",
   "tamanhos": "17 a 22",
   "valor": 45.9,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/infantil/Sapátos",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/59.jfif",
   "urlDrive": "https://drive.google.com/file/d/1RC2JPZofrjblcHRft26Qs5Jz7RFuAqqh/view?usp=share_link"
  },
  {
   "id": 60,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandália ",
   "nomeProduto": "Sandália Bloco",
   "descricao": "Sandália Bloco",
   "tamanhos": "34 a 39",
   "valor": 130,
   "quantParcelasSemJuros": 6,
   "filtroClassificacao": "all/feminino/adulto/Sandália ",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/60.jfif",
   "urlDrive": "https://drive.google.com/file/d/1MsNaDIHWEQeAnkVZv9_tVoAOEL3sZDma/view?usp=share_link"
  },
  {
   "id": 61,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandália ",
   "nomeProduto": "Sandália Bloco",
   "descricao": "Sandália Bloco",
   "tamanhos": "34 a 39",
   "valor": 130,
   "quantParcelasSemJuros": 6,
   "filtroClassificacao": "all/feminino/adulto/Sandália ",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/61.jfif",
   "urlDrive": "https://drive.google.com/file/d/1TnoLed7Wn5882Or4_btMYAf32wns9UEc/view?usp=share_link"
  },
  {
   "id": 62,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandália ",
   "nomeProduto": "Sandália Bloco",
   "descricao": "Sandália Bloco",
   "tamanhos": "34 a 39",
   "valor": 130,
   "quantParcelasSemJuros": 6,
   "filtroClassificacao": "all/feminino/adulto/Sandália ",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/62.jfif",
   "urlDrive": "https://drive.google.com/file/d/1YQk8gnLo33qKYkIN905Mrf8v2reL9qBz/view?usp=share_link"
  },
  {
   "id": 63,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sandália ",
   "nomeProduto": "Sandália Bloco",
   "descricao": "Sandália Bloco",
   "tamanhos": "34 a 39",
   "valor": 130,
   "quantParcelasSemJuros": 6,
   "filtroClassificacao": "all/feminino/adulto/Sandália ",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/63.jfif",
   "urlDrive": "https://drive.google.com/file/d/1mQPsq32XJiod6s4iD8XnrfhuJr9TnN5g/view?usp=share_link"
  },
  {
   "id": 64,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Tamanco",
   "nomeProduto": "Calçado",
   "descricao": "Tamanco Vinil",
   "tamanhos": "34 a 39",
   "valor": 85,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Tamanco",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/64.jfif",
   "urlDrive": "https://drive.google.com/file/d/1CHwbabQlVq3ZztSDByFroeEnmxBDElxp/view?usp=share_link"
  },
  {
   "id": 65,
   "genero": "feminino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Tamanco",
   "nomeProduto": "Calçado",
   "descricao": "Tamanco Vinil",
   "tamanhos": "34 a 39",
   "valor": 85,
   "quantParcelasSemJuros": 2,
   "filtroClassificacao": "all/feminino/adulto/Tamanco",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/65.jfif",
   "urlDrive": "https://drive.google.com/file/d/1rxO0i94QJ0TGem4gNQIumUEdDIb51D5O/view?usp=share_link"
  },
  {
   "id": 66,
   "genero": "masculino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sapátos",
   "nomeProduto": "Air Jodan",
   "descricao": "Jordan - 4º linha - Premium",
   "tamanhos": "38 a 43",
   "valor": 120,
   "quantParcelasSemJuros": 6,
   "filtroClassificacao": "all/masculino/adulto/Sapátos",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/66.jfif",
   "urlDrive": "https://drive.google.com/file/d/1UGqE38vpI1Fl5VnMc4uhgCXpacL7jnM1/view?usp=share_link"
  },
  {
   "id": 67,
   "genero": "masculino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sapátos",
   "nomeProduto": "Air Jodan",
   "descricao": "Jordan - 4º linha - Premium",
   "tamanhos": "38 a 43",
   "valor": 120,
   "quantParcelasSemJuros": 6,
   "filtroClassificacao": "all/masculino/adulto/Sapátos",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/67.jfif",
   "urlDrive": "https://drive.google.com/file/d/1KZIXPQtqoOTJEKMswP8j3SA_TZU35uEu/view?usp=share_link"
  },
  {
   "id": 68,
   "genero": "masculino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sapátos",
   "nomeProduto": "Air Jodan",
   "descricao": "Jordan - 4º linha - Premium",
   "tamanhos": "38 a 43",
   "valor": 120,
   "quantParcelasSemJuros": 6,
   "filtroClassificacao": "all/masculino/adulto/Sapátos",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/68.jfif",
   "urlDrive": "https://drive.google.com/file/d/1GpOfFQ6UVfKajRusVNrUA4eHdhb1v5fD/view?usp=share_link"
  },
  {
   "id": 69,
   "genero": "masculino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sapátos",
   "nomeProduto": "Air Jodan",
   "descricao": "Jordan - 4º linha - Premium",
   "tamanhos": "38 a 43",
   "valor": 120,
   "quantParcelasSemJuros": 6,
   "filtroClassificacao": "all/masculino/adulto/Sapátos",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/69.jfif",
   "urlDrive": "https://drive.google.com/file/d/10OPjyCsKfvx_eSK2GX5tPTWN3rY4nSN8/view?usp=share_link"
  },
  {
   "id": 70,
   "genero": "masculino",
   "faixaEtaria": "adulto",
   "tipoProduto": "Sapátos",
   "nomeProduto": "Air Jodan",
   "descricao": "Jordan - 4º linha - Premium",
   "tamanhos": "38 a 43",
   "valor": 120,
   "quantParcelasSemJuros": 6,
   "filtroClassificacao": "all/masculino/adulto/Sapátos",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/70.jfif",
   "urlDrive": "https://drive.google.com/file/d/1H9nPyzta94G4A7virKD3L6LyYfeaiKhl/view?usp=share_link"
  },
  {
   "id": 71,
   "genero": "feminino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália infantil",
   "descricao": "Mini Melissa",
   "tamanhos": "19 a 26",
   "valor": 69.9,
   "quantParcelasSemJuros": 3,
   "filtroClassificacao": "all/feminino/infantil/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/71.jfif",
   "urlDrive": "https://drive.google.com/file/d/1VdSlnP9PLjw8lbRkisYpV6r5j8BqzbCM/view?usp=share_link"
  },
  {
   "id": 72,
   "genero": "feminino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália infantil",
   "descricao": "Mini Melissa",
   "tamanhos": "19 a 26",
   "valor": 69.9,
   "quantParcelasSemJuros": 3,
   "filtroClassificacao": "all/feminino/infantil/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/72.jfif",
   "urlDrive": "https://drive.google.com/file/d/1iba2b8uBuT33n4Rjf7BmIFHzr4SezJZB/view?usp=share_link"
  },
  {
   "id": 73,
   "genero": "feminino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália infantil",
   "descricao": "Mini Melissa",
   "tamanhos": "19 a 26",
   "valor": 69.9,
   "quantParcelasSemJuros": 3,
   "filtroClassificacao": "all/feminino/infantil/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/73.jfif",
   "urlDrive": "https://drive.google.com/file/d/1KUOu2huTT_y-00whRriEJjaWvVGQFzwJ/view?usp=share_link"
  },
  {
   "id": 74,
   "genero": "feminino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália infantil",
   "descricao": "Mini Melissa",
   "tamanhos": "19 a 26",
   "valor": 69.9,
   "quantParcelasSemJuros": 3,
   "filtroClassificacao": "all/feminino/infantil/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/74.jfif",
   "urlDrive": "https://drive.google.com/file/d/1mqNgMxvNNqo1pKuhXo-cvnywNvAAM8fn/view?usp=share_link"
  },
  {
   "id": 75,
   "genero": "feminino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália infantil",
   "descricao": "Mini Melissa",
   "tamanhos": "19 a 26",
   "valor": 69.9,
   "quantParcelasSemJuros": 3,
   "filtroClassificacao": "all/feminino/infantil/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/75.jfif",
   "urlDrive": "https://drive.google.com/file/d/1zTLC34iF45C3FKRKi7K6njgj1LIlKFWB/view?usp=share_link"
  },
  {
   "id": 76,
   "genero": "feminino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália infantil",
   "descricao": "Mini Melissa",
   "tamanhos": "19 a 26",
   "valor": 69.9,
   "quantParcelasSemJuros": 3,
   "filtroClassificacao": "all/feminino/infantil/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/76.jfif",
   "urlDrive": "https://drive.google.com/file/d/1aZLGY4umK4qjFjRPydMiCH9PWIUiCzM0/view?usp=share_link"
  },
  {
   "id": 77,
   "genero": "feminino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália infantil",
   "descricao": "Mini Melissa",
   "tamanhos": "19 a 26",
   "valor": 69.9,
   "quantParcelasSemJuros": 3,
   "filtroClassificacao": "all/feminino/infantil/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/77.jfif",
   "urlDrive": "https://drive.google.com/file/d/1iZsB3CKFOU3yA9BaaK9TJrQ4baAEXWdn/view?usp=share_link"
  },
  {
   "id": 78,
   "genero": "masculino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália Mar Sandal",
   "descricao": "Percata - Mar sandal",
   "tamanhos": "19 a 26",
   "valor": 69.9,
   "quantParcelasSemJuros": 3,
   "filtroClassificacao": "all/masculino/infantil/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/78.jfif",
   "urlDrive": "https://drive.google.com/file/d/1Pf_e_J2yjO1WlZqVEceIjDrGJ96D_1bI/view?usp=share_link"
  },
  {
   "id": 79,
   "genero": "masculino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália Mar Sandal",
   "descricao": "Percata - Mar sandal",
   "tamanhos": "19 a 26",
   "valor": 69.9,
   "quantParcelasSemJuros": 3,
   "filtroClassificacao": "all/masculino/infantil/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/79.jfif",
   "urlDrive": "https://drive.google.com/file/d/1zrI3GfrbYMq6Wq3j5F4ZWPWfd1GD2rjJ/view?usp=share_link"
  },
  {
   "id": 80,
   "genero": "masculino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália Mar Sandal",
   "descricao": "Percata - Mar sandal",
   "tamanhos": "19 a 26",
   "valor": 69.9,
   "quantParcelasSemJuros": 3,
   "filtroClassificacao": "all/masculino/infantil/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/80.jfif",
   "urlDrive": "https://drive.google.com/file/d/1M_q_VUcBs6vwt94PM-VHv2kHjvfP7WP2/view?usp=share_link"
  },
  {
   "id": 81,
   "genero": "masculino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sandálias",
   "nomeProduto": "Sandália Mar Sandal",
   "descricao": "Percata - Mar sandal",
   "tamanhos": "19 a 26",
   "valor": 69.9,
   "quantParcelasSemJuros": 3,
   "filtroClassificacao": "all/masculino/infantil/Sandálias",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/81.jfif",
   "urlDrive": "https://drive.google.com/file/d/1konv5jYNYQewAIfrBnQXD077wfvo1QF4/view?usp=share_link"
  },
  {
   "id": 82,
   "genero": "masculino",
   "faixaEtaria": "infantil",
   "tipoProduto": "tênis",
   "nomeProduto": "tênis infantil",
   "descricao": "...",
   "tamanhos": "...",
   "valor": 45.9,
   "quantParcelasSemJuros": 3,
   "filtroClassificacao": "all/masculino/infantil/tênis",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/82.jfif",
   "urlDrive": "https://drive.google.com/file/d/1_MLqF2MILelmkcnZLlQWtFdbusMBeHZC/view?usp=share_link"
  },
  {
   "id": 84,
   "genero": "masculino",
   "faixaEtaria": "infantil",
   "tipoProduto": "tênis",
   "nomeProduto": "tênis infantil",
   "descricao": "...",
   "tamanhos": "17 a 22",
   "valor": 45.9,
   "quantParcelasSemJuros": 3,
   "filtroClassificacao": "all/masculino/infantil/tênis",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/84.jfif",
   "urlDrive": "https://drive.google.com/file/d/1HJ8zkn1xgDooFqqKkV73RkeOLEXaM07u/view?usp=share_link"
  },
  {
   "id": 85,
   "genero": "masculino",
   "faixaEtaria": "infantil",
   "tipoProduto": "tênis",
   "nomeProduto": "tênis infantil",
   "descricao": "...",
   "tamanhos": "17 a 22",
   "valor": 45.9,
   "quantParcelasSemJuros": 3,
   "filtroClassificacao": "all/masculino/infantil/tênis",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/85.jfif",
   "urlDrive": "https://drive.google.com/file/d/1dYEh1ilAuEmvvOHBtDL6S_2L941llp3g/view?usp=share_link"
  },
  {
   "id": 86,
   "genero": "feminino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sapátos",
   "nomeProduto": "Sapato Infantil",
   "descricao": "...",
   "tamanhos": "17 a 22",
   "valor": 45.9,
   "quantParcelasSemJuros": 3,
   "filtroClassificacao": "all/feminino/infantil/Sapátos",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/86.jfif",
   "urlDrive": "https://drive.google.com/file/d/1JIXd4pCgH1oP9525ORkgzArxY4_I_gda/view?usp=share_link"
  },
  {
   "id": 87,
   "genero": "feminino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sapátos",
   "nomeProduto": "Sapato Infantil",
   "descricao": "...",
   "tamanhos": "17 a 22",
   "valor": 45.9,
   "quantParcelasSemJuros": 3,
   "filtroClassificacao": "all/feminino/infantil/Sapátos",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/87.jfif",
   "urlDrive": "https://drive.google.com/file/d/1j61GC_CQcMqQaVGfaPV_NxEPR9fpHQIJ/view?usp=share_link"
  },
  {
   "id": 88,
   "genero": "feminino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sapátos",
   "nomeProduto": "Sapato Infantil",
   "descricao": "...",
   "tamanhos": "17 a 22",
   "valor": 45.9,
   "quantParcelasSemJuros": 3,
   "filtroClassificacao": "all/feminino/infantil/Sapátos",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/88.jfif",
   "urlDrive": "https://drive.google.com/file/d/1eawqyhGtWeXsk6FiN5wcXdmok1bbp3gu/view?usp=share_link"
  },
  {
   "id": 89,
   "genero": "feminino",
   "faixaEtaria": "infantil",
   "tipoProduto": "Sapátos",
   "nomeProduto": "Sapato Infantil",
   "descricao": "...",
   "tamanhos": "17 a 22",
   "valor": 45.9,
   "quantParcelasSemJuros": 3,
   "filtroClassificacao": "all/feminino/infantil/Sapátos",
   "urlWhatsapp": "https://wa.me/557197073343?text=Olá!%20fiquei%20interessado(a)%20neste%20item:%20",
   "urlImg": "img/products/assets/89.jfif",
   "urlDrive": "https://drive.google.com/file/d/1jXnGHuCrScT7weUruGq4ZdM3UtNCGXEt/view?usp=share_link"
  }
 ]







const { createApp } = Vue

createApp({
  data() {
    return {
      data: window.data,
      awesome: true,
      teste: true,
      

    
    }

  },

  computed: {
    resultFilters() {
      

      return this.data.filter(results => {if(results.faixaEtaria=='a'){return results}})
    }

  }
}).mount('#app')
